"""Generated-source machinery for the module library's leaf bodies.

Two jobs live here:

- `load_generated`: exec generated source under a linecache-registered
  filename, so `inspect.getsource` returns exactly the generated bytes
  (what any reader sees is what runs). The printer's `to_function` and
  the dispatch wrappers both ride it.
- the uniform-args dispatch wrappers that make a tools table dynamically
  dispatchable: one call site, one compile-time kwargs shape
  (`args: dict`), any tool. Each wrapper embeds the user function's
  source verbatim, so the tool leaf the artifact carries is exactly what
  runs — no closures, no registry, no reach-back.

The old forward string templates are gone: signature-polymorphic modules
now BUILD their forward trees (`dspy.programir.build`) and derive the
native twin from the printer (`dspy.programir.printer.bind_forward`).
"""

from __future__ import annotations

import ast
import inspect
import itertools
import linecache
import textwrap
from typing import Any, Callable

from dspy.adapters.types.tool import Tool
from dspy.core.errors import AdapterParseError, InterpreterError, LMError, ToolError

__all__ = ["ToolTable", "build_dispatch_tool", "load_generated", "normalize_tools"]

_COUNTER = itertools.count(1)

#: The typed-error names a generated forward may catch; seeded into the
#: exec globals so the NATIVE path resolves the same classes the engine's
#: handler names denote.
_FORWARD_GLOBALS = {
    "ToolError": ToolError,
    "InterpreterError": InterpreterError,
    "AdapterParseError": AdapterParseError,
    "LMError": LMError,
}


class ToolTable(dict):
    """A tools table whose unknown-name refusal is the engine's.

    The engine raises `ToolError` for an unknown tool name; a plain dict
    would raise `KeyError` on the native path. `__missing__` closes the
    gap so `except ToolError` behaves identically on both paths.
    """

    def __missing__(self, key):
        raise ToolError(f"unknown tool {key!r}")


def load_generated(source: str, *, tag: str, name: str) -> Callable[..., Any]:
    """Exec generated source under a linecache-registered filename.

    Returns the named function; `inspect.getsource` on it returns the
    exact generated bytes (what the compiler reads is what runs).
    """
    filename = f"<dspy-generated:{tag}:{next(_COUNTER)}>"
    linecache.cache[filename] = (len(source), None, source.splitlines(keepends=True), filename)
    namespace: dict[str, Any] = dict(_FORWARD_GLOBALS)
    exec(compile(source, filename, "exec"), namespace)
    return namespace[name]


def normalize_tools(tools: Any, *, owner: str, reserved: tuple[str, ...]) -> list[Tool]:
    """Coerce a user tools list into named `Tool` specs, refusing loudly.

    Args:
        tools: The user's `tools=[...]` list (callables or Tools).
        owner: The module name, for teaching errors.
        reserved: Names the module owns (`finish`, `submit`, ...).
    """
    if isinstance(tools, dict):
        raise TypeError(f"{owner} takes tools as a list, not a dict; names come from the functions")
    specs = [tool if isinstance(tool, Tool) else Tool(tool) for tool in tools or []]
    seen: set[str] = set()
    for spec in specs:
        name = spec.name
        if not isinstance(name, str) or not name.isidentifier():
            raise ValueError(f"{owner} tool name {name!r} must be a Python identifier")
        if name in reserved:
            raise ValueError(f"{owner} reserves the tool name {name!r} for its own termination move")
        if name in seen:
            raise ValueError(f"{owner} got two tools named {name!r}")
        seen.add(name)
    return specs


def build_dispatch_tool(tool: Tool, *, owner: str) -> Callable[..., Any]:
    """Build the uniform-args dispatch wrapper for one tool.

    The v0.3 subset gives a dynamic tool call site exactly one
    compile-time kwargs shape, so every tool behind
    `self.tools[name](args=...)` must share a calling convention. The
    wrapper takes `(args: dict)`, embeds the user function's source
    verbatim, calls it with `**args`, and converts any failure into the
    typed `ToolError` — identical conduct on the native path and under
    the engine.
    """
    function = tool.func
    name = tool.name
    try:
        original = textwrap.dedent(inspect.getsource(function)).strip()
    except (OSError, TypeError) as error:
        raise ValueError(
            f"{owner} tool {name!r} has no introspectable source; declared tool leaves carry their "
            "source into the artifact — author it as a plain named function"
        ) from error
    tree = ast.parse(original)
    if not tree.body or not isinstance(tree.body[0], ast.FunctionDef):
        raise ValueError(
            f"{owner} tool {name!r} must be a plain named function (lambdas and callables have no declarable source)"
        )
    definition = tree.body[0]
    if definition.returns is None:
        raise ValueError(f"{owner} tool {name!r} is missing a return type hint; tool leaves declare their types")
    returns = ast.unparse(definition.returns)
    inner_name = definition.name
    source = (
        f"def {name}(args: dict) -> {returns}:\n"
        f'    """Uniform-args dispatch for tool {name!r} (one calling convention per dynamic call site)."""\n'
        f"{textwrap.indent(original, '    ')}\n"
        f"    from dspy.core.errors import ToolError\n"
        f"    try:\n"
        f"        result = {inner_name}(**args)\n"
        f"    except ToolError:\n"
        f"        raise\n"
        f"    except Exception as error:\n"
        f'        raise ToolError("Execution error in {name}: " + str(error)) from error\n'
        f"    return result\n"
    )
    return load_generated(source, tag=f"tool-{name}", name=name)
